version: '1.0'
stages:
- Validate
- Build
steps:
  configure_env:
    title: Configure Environment
    image: alpine
    commands:
    - cf_export CI=true
    - env | grep CF_
  install_dependecies:
    title: Install Dependecies
    image: node
    commands:
    - echo node $(node --version)
    - echo npm $(npm --version)
    - echo yarn $(yarn --version)
    - yarn
  validation:
    type: parallel
    title: Validation
    stage: Validate
    steps:
      lint:
        title: Lint
        image: node
        commands:
        - yarn lint
      perform_tests:
        title: Run Tests with Coverage
        image: node
        environment:
        - CODECOV_TOKEN=acd60370-1c28-43f8-96ce-801a884cd204
        commands:
        - yarn cover
        - curl -s https://codecov.io/bash | bash -s
  build_styleguide:
    title: Build Styleguide
    stage: Build
    image: node
    commands:
    - yarn styleguide:build
  run_chromatic:
    title: Run Chromatic
    stage: Build
    image: node
    commands:
    - yarn chromatic --exit-zero-on-changes
